"""distutils_extra.command.clean_i18n

Implements the Distutils 'clean_i18n' command."""

import os.path
from distutils.dir_util import remove_tree
import distutils.command.clean

class clean_i18n(distutils.command.clean.clean):

    description = "clean up files generated by build_i18n"

    def run(self):
        mo_dir =  os.path.join("build", "mo")
        if os.path.isdir(mo_dir):
            remove_tree('build/mo')

        distutils.command.clean.clean.run(self)
